# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets

fcdb = sqlite3.connect('fantasycricket.db')
cursorfc = fcdb.cursor()
cursorfc.execute("SELECT DISTINCT team from teams; ")
tup = cursorfc.fetchall()
records = [item for t in tup for item in t]


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Open Team")
        # Dialog.resize(330, 500)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 400))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetTeam = QtWidgets.QWidget(Dialog)
        self.widgetTeam.setObjectName("widgetTeam")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.widgetTeam)
        self.verticalLayout1.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.widgetTeam)
        self.comboBox.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: blue;")
        self.comboBox.setObjectName("comboBox")
        cursorfc.execute("SELECT DISTINCT team from teams; ")
        tup = cursorfc.fetchall()
        records = [item for t in tup for item in t]
        #added a placeholder before adding names from the list
        self.comboBox.addItem("Select Team")
        self.comboBox.addItems(records)
        self.comboBox.currentIndexChanged.connect(self.selectlist)
        self.verticalLayout1.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.widgetTeam)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("font: 9pt \"Comic Sans MS\";\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(227, 227, 227);\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def selectlist(self):
        teamname = self.comboBox.currentText()
        cursorfc.execute("SELECT name , value FROM teams WHERE team ='"+teamname+"'  ")
        records = cursorfc.fetchall()

        self.tableWidget.setRowCount(len(records))
        rows = len(records)
        for row in range(rows):
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(records[row][0]))
            self.tableWidget.setItem(row,1,QtWidgets.QTableWidgetItem(records[row][1]))




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Open Team"))
        self.comboBox.setPlaceholderText(_translate("Dialog", "Select Team"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Player Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
